### ISSUE TITLE
AuthGuard bugs

### ISSUE THREAD

**Issue by mrdiamond12312** [thuanbkk20/e-neighbor-backend#19]
## Expected Behavior

If user information was change, the user's infomation should be up-to-date with current in database.
## Current Behavior

User Information was read from Jwt, which save everything about the user, and later use after user have updated their information
## Possible Solution

Jwt should only save what is unchanged (PRIMARY_KEY such as userId).
## Steps to Reproduce

1. Start up server
2. Register and Login as user -> which will  generate a jwt
3. Onboard the account as Lessor (using 'POST /on-board' or POST '/')
4. Now, just simply get user profile (using 'GET /profile') and got the account role as 'user'

## Context

- This may make userflow gone wrong, for example, lessor onboarding and still remain as a user.
- At Client, we only have 1 login window, 1 place to store accessToken, and as discussed before, lessor can also act as user, so there's no need to seperate the login method (instead of admin), or if we integrate with GGOAuth, we need to implement based on this implementation.

## Affected Routes
- [ ] Any Route that are Guard with 'user' for throwing exception or 'lessor' for continuing a transaction.

## Possible Implementation
- [ ] Sign only user.id in jwt
- [ ] Refactor Payload in AuthGuard
- [ ] Any service that change userInfo will need to setAuthUser(). (may not affect at all, because it's based on jwt).
### OR

- Return Highest role of the account only using /login, ClientSide will logout the user as they change anything (or server return new jwt)

## Affected Routes with First Implementation
- [ ] 'GET /profile' as it based on express-ctx
- [ ] 'POST /auth/lessor-login' -> rmv

## With Second Implementation
- [x] 'POST /auth/login' sign jwt with highest current role of the account.
- [x] 'POST /on-boarding' will change the role of user to lessor and return a new jwt
- [ ] 'POST /profile/update' will return a new jwt

**Comment by thuanbkk20** [comment]
Thank you for bringing this issue to my attention.
## Root of the problem
Initially, I split user login and lessor login into two separate APIs and signed the returned JWT with the corresponding role. The `AuthGuard` I implemented finds the user with the ID and role extracted from the JWT and then calls `setAuthUser()`. This leads to a situation where, even after lessor onboarding, if 'GET /profile' is called with the JWT from 'POST /auth/login', the role returned remains 'user'.
## Solution
- [X] Remove 'POST /auth/lessor-login' 
- [X] 'POST /auth/login' sign jwt with highest current role of the account.
- [X] 'POST /lessor' or 'POST /lessor/onboard' return a new jwt.
